---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install: gem install bundler -v 2.0.2
services:
  - postgresql
before_script:
  - psql -c 'create database dummy_test;' -U postgres
  - RAILS_ENV=test rails db:migrate
